# Generated by Django 5.1.7 on 2025-03-31 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='conversation_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AudioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='chatbot.chatsession')),
            ],
        ),
    ]
