# Generated by Django 5.1.7 on 2025-03-31 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='title',
        ),
    ]
