# Generated by Django 5.1.7 on 2025-03-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
