# Generated by Django 5.1.7 on 2025-04-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatmessage_conversation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
