# Generated by Django 5.1.7 on 2025-04-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_imageupload_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('document', 'Document')], default='text', max_length=10),
        ),
    ]
