# Generated by Django 5.1.7 on 2025-04-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chatmessage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='type',
        ),
    ]
