# Generated by Django 5.1.7 on 2025-04-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_chatmessage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Conversation', max_length=255),
        ),
    ]
