# Generated by Django 5.1.7 on 2025-04-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
