# Generated by Django 5.1.7 on 2025-04-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_chatmessage_title_alter_chatsession_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='title',
        ),
    ]
