# Generated by Django 5.1.7 on 2025-04-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_remove_chatsession_title_alter_audioupload_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioupload',
            name='audio_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
