# Generated by Django 5.1.7 on 2025-04-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_audioupload_audio_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioupload',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='document',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='image',
        ),
    ]
